# -*- coding: utf-8 -*-
"""Monte Carlo Loan Portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPxN-Xpj5I4WMKtqiRyCrtXx36FX38_1
"""

import numpy as np
import pandas as pd
from scipy.stats import norm
from datetime import timedelta
import matplotlib.pyplot as plt
import seaborn as sns

# Set random seed for reproducibility
np.random.seed(20260529)

"""# 1. ASSUMPTIONS & PARAMETERS

The Main parameters are the:


1.   The number of Borrowers in the portfolio
2.   The Time Period
3.   The sensitivity to macro factors
"""

START_DATE = pd.to_datetime("2018-01-01")
END_DATE = pd.to_datetime("2026-05-31")
N_BORROWERS = 1500
RHO = 0.15  # Asset correlation (Sensitivity to macroeconomic factors)

# Generate a daily Macroeconomic Factor (Y) from 2018 to May 2026
# We use a smoothed random walk to represent economic cycles (bull/bear periods)
date_range = pd.date_range(start=START_DATE, end=END_DATE)
raw_macro = np.random.normal(0, 1, len(date_range))
# Smooth over 30 days to create realistic economic trends rather than daily noise
smoothed_macro = pd.Series(raw_macro).rolling(window=30, min_periods=1).mean()
# Normalize back to mean 0, std 1
MACRO_FACTOR = (smoothed_macro - smoothed_macro.mean()) / smoothed_macro.std()
macro_dict = dict(zip(date_range.date, MACRO_FACTOR))

# Weights for Baseline Probability of Default (Logistic formulation)
# Positive weight = Increases chance of being late/defaulting
WEIGHTS = {
    'intercept': 2.5,
    'credit_score': -0.008,      # Strong negative impact on risk
    'age': -0.015,               # Slight negative impact
    'log_income': -0.3,          # Higher income lowers risk
    'log_amount': 0.25,          # Larger loans are slightly riskier
    'tenure_penalty': 0.003,     # Longer loans slightly riskier
    'good_history': -0.15,       # Previous good payments lower risk
    'super_bonus': -0.4,         # 'Super' borrowers inherently less risky
    'oneoff_penalty': 0.3,       # 'Oneoff' inherently riskier
    # --- NEW DEMOGRAPHIC / FINANCIAL WEIGHTS ---
    'dti_penalty': 2.0,          # High Debt-to-Income drastically increases risk
    'unemployed_penalty': 0.8,   # Lack of stable job increases risk
    'log_net_worth': -0.05,      # Wealth buffer slightly reduces risk
    'dependents_penalty': 0.05   # More dependents slightly strains disposable income
}

"""# 2. GENERATE BORROWERS"""

print("Generating borrowers with demographic profiles...")
borrower_types = np.random.choice(["super", "occasional", "oneoff"], size=N_BORROWERS, p=[0.15, 0.55, 0.30])
ages = np.random.randint(18, 70, size=N_BORROWERS)
genders = np.random.choice(["M", "F"], size=N_BORROWERS)

# Correlate Income and Credit Score slightly with Borrower Type
incomes = []
credit_scores = []
for b_type in borrower_types:
    if b_type == "super":
        inc = np.random.lognormal(mean=np.log(60000), sigma=0.5)
        cs = min(max(int(np.random.normal(720, 50)), 300), 850)
    elif b_type == "occasional":
        inc = np.random.lognormal(mean=np.log(40000), sigma=0.6)
        cs = min(max(int(np.random.normal(650, 70)), 300), 850)
    else:
        inc = np.random.lognormal(mean=np.log(25000), sigma=0.7)
        cs = min(max(int(np.random.normal(580, 80)), 300), 850)
    incomes.append(inc)
    credit_scores.append(cs)

# --- NEW KAGGLE-STYLE DEMOGRAPHICS & FINANCIALS ---
experiences = np.maximum(0, ages - np.random.randint(18, 24, size=N_BORROWERS))
job_tenures = [np.round(np.random.uniform(0, exp), 1) if exp > 0 else 0 for exp in experiences]
emp_status = np.random.choice(["Employed", "Self-Employed", "Unemployed"], size=N_BORROWERS, p=[0.7, 0.2, 0.1])
edu_levels = np.random.choice(["High School", "Bachelor", "Master", "PhD"], size=N_BORROWERS, p=[0.4, 0.4, 0.15, 0.05])
marital_status = np.random.choice(["Single", "Married", "Divorced"], size=N_BORROWERS, p=[0.4, 0.5, 0.1])
dependents = np.random.randint(0, 6, size=N_BORROWERS)

# Advanced Financials
monthly_incomes = np.array(incomes) / 12
dtis = np.random.uniform(0.05, 0.5, size=N_BORROWERS)
monthly_debts = monthly_incomes * dtis

checking_acc = monthly_incomes * np.random.uniform(0.1, 2.0, size=N_BORROWERS)
savings_acc = monthly_incomes * np.random.uniform(0, 10.0, size=N_BORROWERS)
total_assets = np.array(incomes) * np.random.uniform(0.5, 5.0, size=N_BORROWERS) + checking_acc + savings_acc
total_liabilities = monthly_debts * 12 * np.random.uniform(1.0, 5.0, size=N_BORROWERS)
net_worths = total_assets - total_liabilities

# Credit History specific
open_lines = np.random.randint(1, 10, size=N_BORROWERS)
crb_inquiries = np.random.randint(0, 5, size=N_BORROWERS)
credit_hist_length = np.maximum(0, ages - 18)

borrowers = pd.DataFrame({
    'borrower_id': range(1, N_BORROWERS + 1),
    'borrower_type': borrower_types,
    'age': ages,
    'gender': genders,
    'annual_income': incomes,
    'credit_score': credit_scores,
    'employment_status': emp_status,
    'education_level': edu_levels,
    'experience': experiences,
    'marital_status': marital_status,
    'number_of_dependents': dependents,
    'monthly_debt_payments': monthly_debts,
    'number_of_open_credit_lines': open_lines,
    'number_of_crbs': crb_inquiries,
    'length_of_credit_history': credit_hist_length,
    'savings_account_balance': savings_acc,
    'checking_account_balance': checking_acc,
    'total_assets': total_assets,
    'total_liabilities': total_liabilities,
    'job_tenure': job_tenures,
    'net_worth': net_worths,
    'risk_re': np.random.normal(0, 0.7, N_BORROWERS) # Individual latent risk factor
})

"""# 3. SIMULATION ENGINE"""

def simulate_loans_one_borrower(b):
    out = []

    # Determine target number of loans
    if b.borrower_type == "oneoff":
        target_loans = 1
    elif b.borrower_type == "occasional":
        target_loans = min(max(np.random.poisson(2) + 1, 2), 15)
    else: # super
        target_loans = min(max(np.random.poisson(18) + 1, 8), 45)

    first_offset = np.random.randint(0, 365 * 3)
    loan_date = START_DATE + timedelta(days=first_offset)

    if loan_date > (END_DATE - timedelta(days=365)):
        return out

    cum_good = 0
    prev_payoff = pd.NaT

    for j in range(1, target_loans + 1):
        if j > 1:
            lag_base = {"oneoff": 9999, "occasional": 90, "super": 25}[b.borrower_type]
            gap_days = max(1, int(np.round(np.random.gamma(shape=2, scale=lag_base/2))))
            loan_date = prev_payoff + timedelta(days=gap_days)

        if loan_date > (END_DATE - timedelta(days=365)):
            break

        # Tenure
        t_probs = {
            "oneoff": [0.15, 0.35, 0.25, 0.15, 0.08, 0.02],
            "occasional": [0.10, 0.30, 0.30, 0.18, 0.10, 0.02],
            "super": [0.05, 0.20, 0.30, 0.25, 0.15, 0.05]
        }[b.borrower_type]
        tenure_days = np.random.choice([14, 30, 60, 90, 180, 365], p=t_probs)
        due_date = loan_date + timedelta(days=int(tenure_days))

        if due_date > END_DATE:
            break

        # Amount Calculation
        base_amt = {"oneoff": 7000, "occasional": 12000, "super": 22000}[b.borrower_type]
        amount_kes = np.exp(np.log(base_amt) + 0.12 * np.log1p(j) + 0.10 * cum_good + np.random.normal(0, 0.45))
        amount_kes = min(max(amount_kes, 1000), 250000)

        # --- PRE-APPROVAL LOGIC (LoanApproved feature) ---
        dti = b.monthly_debt_payments / (b.annual_income / 12) if b.annual_income > 0 else 1.0
        loan_approved = 1

        # Hard rejection criteria based on financials
        if dti > 0.55:
            loan_approved = 0
        elif b.employment_status == "Unemployed" and b.savings_account_balance < (amount_kes * 0.2):
            loan_approved = 0

        if loan_approved == 0:
            out.append({
                'borrower_id': b.borrower_id,
                'borrower_type': b.borrower_type,
                'Age': b.age,
                'Gender': b.gender,
                'AnnualIncome': round(b.annual_income, 2),
                'CreditScore': b.credit_score,
                'EmploymentStatus': b.employment_status,
                'EducationLevel': b.education_level,
                'Experience': b.experience,
                'MaritalStatus': b.marital_status,
                'NumberOfDependents': b.number_of_dependents,
                'MonthlyDebtPayments': round(b.monthly_debt_payments, 2),
                'NumberOfOpenCreditLines': b.number_of_open_credit_lines,
                'NumberOfCRBs': b.number_of_crbs,
                'LengthOfCreditHistory': b.length_of_credit_history,
                'SavingsAccountBalance': round(b.savings_account_balance, 2),
                'CheckingAccountBalance': round(b.checking_account_balance, 2),
                'TotalAssets': round(b.total_assets, 2),
                'TotalLiabilities': round(b.total_liabilities, 2),
                'JobTenure': b.job_tenure,
                'NetWorth': round(b.net_worth, 2),
                'LoanAmount': round(amount_kes, 2),
                'LoanDuration': tenure_days,
                'LoanApproved': 0,
                'PreviousLoanDefaults': j - 1 - cum_good,
                'PaymentHistory': cum_good,
                'loan_date': loan_date,
                'due_date': np.nan,
                'payoff_date': np.nan,
                'days_late': np.nan,
                'on_time': np.nan,
                'baseline_pd': np.nan,
                'simulated_Z': np.nan
            })
            # Assume rejection delays the next application
            prev_payoff = loan_date + timedelta(days=180)
            continue

        # --- MONTE CARLO RISK EVALUATION (VASICEK MODEL) ---
        # 1. Calculate Baseline linear predictor (Logit) based on borrower profile & loan traits
        type_mod = WEIGHTS['super_bonus'] if b.borrower_type == 'super' else (WEIGHTS['oneoff_penalty'] if b.borrower_type == 'oneoff' else 0)
        unemp_mod = WEIGHTS['unemployed_penalty'] if b.employment_status == "Unemployed" else 0
        net_worth_mod = np.log(max(b.net_worth, 1000)) * WEIGHTS['log_net_worth'] if b.net_worth > 0 else 0

        linpred = (
            WEIGHTS['intercept'] +
            WEIGHTS['credit_score'] * b.credit_score +
            WEIGHTS['age'] * b.age +
            WEIGHTS['log_income'] * np.log(b.annual_income) +
            WEIGHTS['log_amount'] * np.log(amount_kes / 1000) +
            WEIGHTS['tenure_penalty'] * (tenure_days - 30) +
            WEIGHTS['good_history'] * cum_good +
            WEIGHTS['dti_penalty'] * dti +
            unemp_mod +
            net_worth_mod +
            WEIGHTS['dependents_penalty'] * b.number_of_dependents +
            type_mod + b.risk_re
        )

        # 2. Convert to Probability of Default (PD)
        baseline_pd = 1 / (1 + np.exp(-linpred))

        # 3. Convert PD to Standard Normal Threshold
        # Cap PD to prevent infinity errors in norm.ppf
        baseline_pd = min(max(baseline_pd, 0.0001), 0.9999)
        threshold = norm.ppf(baseline_pd)

        # 4. Fetch the Macroeconomic state for the due date
        Y = macro_dict.get(due_date.date(), 0)

        # 5. Draw idiosyncratic borrower shock
        epsilon = np.random.normal(0, 1)

        # 6. Calculate Latent Asset Value (Z)
        Z = np.sqrt(RHO) * Y + np.sqrt(1 - RHO) * epsilon

        # 7. Check if loan is late (Z drops below threshold)
        is_late = int(Z < threshold)

        if is_late:
            delay_days = min(int(np.round(np.random.gamma(2.0, scale=18))), 180)
        else:
            delay_days = -min(int(np.round(np.random.gamma(2.5, scale=3))), 10)

        payoff_date = due_date + timedelta(days=delay_days)
        if payoff_date > END_DATE:
            payoff_date = END_DATE

        days_late = (payoff_date - due_date).days
        on_time = int(days_late <= 0)

        gap_since_prev = np.nan if pd.isna(prev_payoff) else (loan_date - prev_payoff).days

        out.append({
            'borrower_id': b.borrower_id,
            'borrower_type': b.borrower_type,
            'Age': b.age,
            'Gender': b.gender,
            'AnnualIncome': round(b.annual_income, 2),
            'CreditScore': b.credit_score,
            'EmploymentStatus': b.employment_status,
            'EducationLevel': b.education_level,
            'Experience': b.experience,
            'MaritalStatus': b.marital_status,
            'NumberOfDependents': b.number_of_dependents,
            'MonthlyDebtPayments': round(b.monthly_debt_payments, 2),
            'NumberOfOpenCreditLines': b.number_of_open_credit_lines,
            'NumberOfCRBs': b.number_of_crbs,
            'LengthOfCreditHistory': b.length_of_credit_history,
            'SavingsAccountBalance': round(b.savings_account_balance, 2),
            'CheckingAccountBalance': round(b.checking_account_balance, 2),
            'TotalAssets': round(b.total_assets, 2),
            'TotalLiabilities': round(b.total_liabilities, 2),
            'JobTenure': b.job_tenure,
            'NetWorth': round(b.net_worth, 2),
            'LoanAmount': round(amount_kes, 2),
            'LoanDuration': tenure_days,
            'LoanApproved': 1,
            'PreviousLoanDefaults': j - 1 - cum_good,
            'PaymentHistory': cum_good,
            'loan_date': loan_date,
            'due_date': due_date,
            'payoff_date': payoff_date,
            'days_late': days_late,
            'on_time': on_time,
            'prior_loans': j - 1,
            'prior_on_time_rate': np.nan if j == 1 else (cum_good / (j - 1)),
            'gap_since_prev_loan': gap_since_prev,
            'baseline_pd': round(baseline_pd, 4),
            'macro_factor_Y': round(Y, 4),
            'simulated_Z': round(Z, 4)
        })

        prev_payoff = payoff_date
        cum_good += on_time

    return out

print("Simulating loan portfolios. This may take a moment...")
all_loans = []
for idx, row in borrowers.iterrows():
    all_loans.extend(simulate_loans_one_borrower(row))

loan_panel = pd.DataFrame(all_loans)

"""# 4. SUMMARIES AND ANALYSIS"""

print("\n--- PORTFOLIO SUMMARY ---")
portfolio_summary = {
    'n_borrowers': loan_panel['borrower_id'].nunique(),
    'n_loans': len(loan_panel),
    'approval_rate': loan_panel['LoanApproved'].mean(),
    'mean_amount': loan_panel['LoanAmount'].mean(),
    'median_amount': loan_panel['LoanAmount'].median(),
    'on_time_rate': loan_panel['on_time'].mean(),
    'avg_baseline_pd': loan_panel['baseline_pd'].mean()
}
for k, v in portfolio_summary.items():
    print(f"{k}: {round(v, 2) if isinstance(v, float) else v}")

print("\n--- SUMMARY BY TYPE ---")
by_type = loan_panel.groupby('borrower_type').agg(
    n_borrowers=('borrower_id', 'nunique'),
    n_loans=('borrower_id', 'count'),
    approval_rate=('LoanApproved', 'mean'),
    mean_amount=('LoanAmount', 'mean'),
    on_time_rate=('on_time', 'mean'),
    avg_credit_score=('CreditScore', 'mean')
).reset_index()
print(by_type.to_string(index=False))

"""# 5. VISUALIZATIONS"""

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: Number of Loans per Borrower
borrower_counts = loan_panel.groupby(['borrower_id', 'borrower_type']).size().reset_index(name='n_loans')
sns.histplot(data=borrower_counts, x='n_loans', hue='borrower_type', multiple="stack", bins=30, ax=axes[0, 0])
axes[0, 0].set_title("Number of Loans per Borrower")

# Plot 2: Macroeconomic Factor Over Time vs Average Daily Default Rate
daily_stats = loan_panel.dropna(subset=['on_time']).groupby('due_date').agg(
    default_rate=('on_time', lambda x: 1 - x.mean()),
    Y=('macro_factor_Y', 'mean')
).reset_index()

ax2 = axes[0, 1].twinx()
sns.lineplot(data=daily_stats, x='due_date', y='Y', color='blue', alpha=0.3, ax=axes[0, 1])
sns.scatterplot(data=daily_stats, x='due_date', y='default_rate', color='red', s=10, alpha=0.5, ax=ax2)
axes[0, 1].set_ylabel('Macro Economic Factor (Y)', color='blue')
ax2.set_ylabel('Daily Default Rate', color='red')
axes[0, 1].set_title("Systemic Macro Factor vs Daily Default Rates")

# Plot 3: Credit Score vs Baseline PD
sns.scatterplot(data=loan_panel.dropna(subset=['baseline_pd']).sample(min(5000, len(loan_panel.dropna(subset=['baseline_pd'])))), x='CreditScore', y='baseline_pd', hue='borrower_type', alpha=0.5, ax=axes[1, 0])
axes[1, 0].set_title("Credit Score vs Baseline Probability of Default")

# Plot 4: Loan Amount by Type
sns.boxplot(data=loan_panel, x='borrower_type', y='LoanAmount', ax=axes[1, 1])
axes[1, 1].set_title("Loan Amount Distribution by Borrower Type")

plt.tight_layout()
plt.show()

# Optional: Export to CSV for Kaggle/Analysis
# loan_panel.to_csv("monte_carlo_loan_simulation_2018_2026.csv", index=False)
print("\nSimulation complete. Data ready for analysis.")

loan_panel.to_csv('simulated_loan_data.csv', index=False)
print("Simulated loan data saved to 'simulated_loan_data.csv'")